import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { PrimeReactProvider } from 'primereact/api';
import 'primereact/resources/themes/arya-blue/theme.css';
import './globals.css';

const roboto = Roboto({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const value = {
  // filterMatchMode: {
  //   text: [
  //     FilterMatchMode.STARTS_WITH,
  //     FilterMatchMode.CONTAINS,
  //     FilterMatchMode.NOT_CONTAINS,
  //     FilterMatchMode.ENDS_WITH,
  //     FilterMatchMode.EQUALS,
  //     FilterMatchMode.NOT_EQUALS,
  //   ],
  //   numeric: [
  //     FilterMatchMode.EQUALS,
  //     FilterMatchMode.NOT_EQUALS,
  //     FilterMatchMode.LESS_THAN,
  //     FilterMatchMode.LESS_THAN_OR_EQUAL_TO,
  //     FilterMatchMode.GREATER_THAN,
  //     FilterMatchMode.GREATER_THAN_OR_EQUAL_TO,
  //   ],
  //   date: [
  //     FilterMatchMode.DATE_IS,
  //     FilterMatchMode.DATE_IS_NOT,
  //     FilterMatchMode.DATE_BEFORE,
  //     FilterMatchMode.DATE_AFTER,
  //   ],
  ripple: true,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <PrimeReactProvider>
        <body className={roboto.className}>{children}</body>
      </PrimeReactProvider>
    </html>
  );
}
