import type { Metadata } from 'next';
import './globals.css';
import { Providers } from './providers';
import "reflect-metadata"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='light'>
      <head>
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"/>

      </head>
      <body className='light text-foreground bg-backgroumd'>
        <Providers>
          { children }
        </Providers>
      </body>
    </html>
  )
}
